name: Lint, Test and Deploy
on: push
jobs:
  lint:
    runs-on: windows-latest
    steps:
    - name: Get code
      uses: actions/checkout@v3
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Run linters
      uses: wearerequired/lint-action@v2
  test:
    needs: lint
    runs-on: windows-latest
    steps:
    - name: Get code
      uses: actions/checkout@v3
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
  deploy: 
    needs: test
    runs-on: windows-latest
    steps:
    - name: Get code
      uses: actions/checkout@v3
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build
    - name: Deploy
      run: echo "Deploying ..."
    
      